### ISSUE TITLE
可以提供一个使用 mock 的 demo 吗？

### ISSUE THREAD

**Issue by simplees** [hanan198501/vue-spa-template#5]
您好：
  谢谢分享一个这么详细的 vue template。因为刚刚学习使用 vue 做 spa 页面开发，受益匪浅。
  但是有点愚钝，通过 express 做 mock 这里有点不是很理解，可以在您空闲的时候做个 demo 或者详细说一下吗？
  拜谢。

**Comment by zzm1988** [comment]
同求demo
