### ISSUE TITLE
master分支上，package.json文件里，开发本地环境里运行 node run dev，缺少包文件"babel-runtime"

### ISSUE THREAD

**Issue by wwb568109135** [hanan198501/vue-spa-template#7]
master分支上，package.json文件里，开发本地环境里运行 node run dev，缺少包文件"babel-runtime"

ERROR in ./~/.npminstall/babel-loader/6.2.8/babel-loader/lib!./~/.npminstall/vue-loader/9.9.5/vue-loader/lib/selector.js?type=script&index=0!./src/views/hello.vue
Module not found: Error: Cannot resolve module 'babel-runtime/regenerator' in /Users/jerry/demo/vue-spa-template/src/views
 @ ./~/.npminstall/babel-loader/6.2.8/babel-loader/lib!./~/.npminstall/vue-loader/9.9.5/vue-loader/lib/selector.js?type=script&index=0!./src/views/hello.vue 7:19-55

ERROR in ./~/.npminstall/babel-loader/6.2.8/babel-loader/lib!./~/.npminstall/vue-loader/9.9.5/vue-loader/lib/selector.js?type=script&index=0!./src/views/hello.vue
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/asyncToGenerator' in /Users/jerry/demo/vue-spa-template/src/views
 @ ./~/.npminstall/babel-loader/6.2.8/babel-loader/lib!./~/.npminstall/vue-loader/9.9.5/vue-loader/lib/selector.js?type=script&index=0!./src/views/hello.vue 11:25-74

**Comment by hanan198501** [comment]
请正确安装 node 依赖包。
