### ISSUE TITLE
按照安装方法正常安装后npm run dev 执行时报错error

### ISSUE THREAD

**Issue by feifanyajun** [hanan198501/vue-spa-template#8]
16 verbose cwd E:\project\vue-spa-template
17 error Windows_NT 10.0.14393
18 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error my-first-vue-app@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the my-first-vue-app@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the my-first-vue-app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs my-first-vue-app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls my-first-vue-app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hanan198501** [comment]
更下下 npm 试试

**Comment by lzou** [comment]
cd到node是安装目录下的node_modules/npm. 执行：`node cli.js install cnpm -g --registry=https://registry.npm.taobao.org`
